apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: svt-system
resources:
  - backend-deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - anomaly-worker-scaledobject.yaml
  - postgres-backup-cronjob.yaml
  - grafana-dashboards-configmap.yaml
  - grafana-deployment.yaml
  - grafana-provisioning-configmap.yaml
images:
  - name: ARTIFACT_REGISTRY_IMAGE
    newName: REGION-docker.pkg.dev/PROJECT/svt/backend
    newTag: latest
